# This is a config for E2B sandbox template.
# You can use template ID (l0o1ltpyc6c2bivs4h4z) or template name (vibe-nextjs-testZ) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-testZ") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-testZ") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-testZ')

team_id = "3215cbee-2748-4363-ad8e-caea2ce82fb7"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-testZ"
template_id = "l0o1ltpyc6c2bivs4h4z"
